---
# title: "info"
# author: "Zhen Li"
# date: "June 1, 2018"
output:
  html_document:
    toc: true
    toc_float: true
    css: style.css
---

```{r setup, echo=F}
knitr::opts_chunk$set(cache = TRUE)
setwd("~/zhenli.name/")
library(DT)
library(openxlsx)
```


<!-- In this page, you will find various useful resources related to single cell genomics, including: -->

<!-- * [List of human neocortex single cell RNA-seq datasets](#anchor1) -->
<!-- * [List of human organoid single cell RNA-seq datasets](#anchor2) -->
<!-- * List of mouse single cell RNA-seq datasets -->
<!-- * List of single cell genomics datasets -->

---

#Single cell RNA-seq Datasets {.tabset}

##Human 
<div style="padding: 20px">

```{r, echo=F}
dt <- read.xlsx("./single_cell_RNA-seq.xlsx",sheet = 1,rowNames = F)
datatable(dt, escape = F, options  = list(autoWidth = T))
```
</div>

##Mouse 
<div style="padding: 20px">

```{r, echo=F}
dt <- read.xlsx("./single_cell_RNA-seq.xlsx",sheet = 2,rowNames = F)
datatable(dt, escape = F, options  = list(autoWidth = T))
```
</div>

##Human organoid 
<div style="padding: 20px">
```{r, echo=F}
dt <- read.xlsx("./single_cell_RNA-seq.xlsx",sheet = 3,rowNames = F)
datatable(dt, escape = F, options  = list(autoWidth = T))
```
</div>

---

#Other resources that I personally use a lot

<div>
<div class="column left" style="background-color:#aaa;"> 
<a href="http://www.brainspan.org/">BrainSpan</a>
</div>

<div class="column right" style="background-color:#bbb;">
<p>A large transcriptome database of the developing human brain.<p>
</div>

</div>

<div><a href="http://hbatlas.org/mouseNCXtranscriptome/">Mouse Neocortical Transcriptome</a></div>
<div><a href="http://psychencode.org/">PsychENCODE</a></div>
<div><a href="https://david.ncifcrf.gov/home.jsp/">DAVID Gene Ontology</a></div>